docker-wp:
  image: wordpress
  links:
   - mysql
  environment:
   - WORDPRESS_DB_PASSWORD=password
  volumes:
   - ./:/var/www/html
  ports:
   - "8080:80"
mysql:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=wordpress
